#!/usr/bin/env ruby

RAILS_ENV = 'development'
require File.dirname(__FILE__) + '/../config/environment'
 
if ARGV.size != 4 
  puts "Available accouts: "
  for person in Person.find(:all)
    puts "#{person.stringid}\t#{person.name}\t#{person.email}" 
  end

  puts "To add new users, call ./insert_user <stringid> <name> <email> <password>"
else
  p = Person.new
  p.stringid = ARGV[0]
  p.name = ARGV[1]
  p.email = ARGV[2]
  p.password = ARGV[3]
  p.save

  puts "Saved User <#{ARGV[0]} to database!"
end
